### ISSUE TITLE
Fix Casting Cost Discount Issue

### ISSUE THREAD

**Issue by sIKE23** [sIKE23/Mage-Wars#120]
If a player chooses not to pay for a spell the has a Discount the code still marks the Discount as used. The same goes for if the player does not have enough mana to pay for the spell the code still marks the Discount as used.

Lines 1852 and 1857 have comments about this issue would you please replace them with the needed code.

**Comment by lettucemode** [comment]
This issue should be resolved, let me know how testing goes

**Comment by sIKE23** [comment]
Much closer, but got this weirdness. I pulled out an Enchantment to test Enchanters Ring and it included Eisenach's Forge Hammer though it shouldn't of.

![enchantment](https://cloud.githubusercontent.com/assets/5695175/5593960/2622e42c-91f7-11e4-8377-0a2603a39ffd.jpg)

**Comment by sIKE23** [comment]
Output from the Chat Window:

sike23 moves 'Retaliate' to Table
debug: Casting Cost:2 and Reveal Cost:2
casting discount testlist: ['Enchantment', '', 'War']
lines: ['Once per round, this Mage may pay 1 less mana when he, or a spawnpoint he controls, casts a soldier spell.\r\n', ' [1] [Soldier] [x1]']
cell entry: 1
cell entry: Soldier
cell entry: x1
cell entry: 
testing req Soldier
casting discount testlist: ['Enchantment', '', 'War']
casting discount testlist: ['Enchantment', '', 'War']
lines: ['Once per round, this Mage may pay 1 less mana when he casts an enchantment spell that targets a friendly creature. \r\n', ' [1] [Enchantment] [x1]']
cell entry: 1
cell entry: Enchantment
cell entry: x1
cell entry: 
testing req Enchantment
debug: Casting Cost:2 and Reveal Cost:2
casting discount testlist: ['Enchantment', '', 'War']
lines: ['Once per round, this Mage may pay 1 less mana when he, or a spawnpoint he controls, casts a soldier spell.\r\n', ' [1] [Soldier] [x1]']
cell entry: 1
cell entry: Soldier
cell entry: x1
cell entry: 
testing req Soldier
casting discount testlist: ['Enchantment', '', 'War']
casting discount testlist: ['Enchantment', '', 'War']
lines: ['Once per round, this Mage may pay 1 less mana when he casts an enchantment spell that targets a friendly creature. \r\n', ' [1] [Enchantment] [x1]']
cell entry: 1
cell entry: Enchantment
cell entry: x1
cell entry: 
testing req Enchantment

**Comment by sIKE23** [comment]
This is a problem with the Dialog code for Discounts not an issue with your code in and of itself. I am trying to resolve.

**Comment by sIKE23** [comment]
Sat an looked at this for a couple of hours, no luck, I know what is happening, but I am not sure of how to resolve.... :(

**Comment by sIKE23** [comment]
Fixed and Closing
