### ISSUE TITLE
Expected Damage Module

### ISSUE THREAD

**Issue by anandaguneratne** [sIKE23/Mage-Wars#125]
It is pretty easy to calculate the expected damage for an attack given the number of dice and amount of armor. Giving players the ability to check this (quickly, obviously) would help new and old players alike make smarter tactical choices.

Notes:
- It is essential that checking expected damage be very quick to do, so that players don't drag down games with calculations. The most promising method that I have come up with is by showing a tooltip when declaring an attack with the targeting arrow, though it is trickier to do this when the creature has multiple attacks.

**Comment by anandaguneratne** [comment]
The code for computing expected damage and chance to kill is complete; now it just needs to be integrated into the octgn module. See https://github.com/sIKE23/Mage-Wars/commit/d85938a4c909c76fedacf52b711c42830d46819b

**Comment by anandaguneratne** [comment]
The expected damage module is integrated into OCTGN! (see https://github.com/sIKE23/Mage-Wars/commit/a8ef7afdd79c0f189c9faaa74757199c71f8135e) Also, I don't know if this is relevant to what you are doing, but the getStat() function did not work due to using the wrong delimiter, so I fixed it. There is still a lot of work to be done fixing anticipated bugs with this module of course - at the moment, I can only say for sure that it works on non-mage creatures and conjurations that have life and integer-valued armor.

**Comment by sIKE23** [comment]
Very slick! Like this very much, what do you think of the text formatting?

**Comment by anandaguneratne** [comment]
Text formatting is nice; I was thinking that it would be nice to make the buttons larger. I wish we could change the font to make it larger.

Also, the button to roll dice is great, but I can't see the graphic.

The attachCards module does not appear to be integrated into Q1 - 2015; is this the case?

**Comment by sIKE23** [comment]
You will find the button under the ImageDatabase folder in the Core set
(starts with eb) Cards folder.

I merged the Master Branch into Q1--2015 and didn't really see any
differences....I will look at it in a bit to see if I can figure out what
has happened.

//FC

**Comment by anandaguneratne** [comment]
I think this is entangled enough with #144 that we don't need a separate issue.
