### ISSUE TITLE
Select Dice Rolls via Buttons

### ISSUE THREAD

**Issue by ACG8** [sIKE23/Mage-Wars#126]
The current interface for declaring attacks requires the user to type in the number of dice they wish to roll. The process would be made faster if the user had the option to click on a button corresponding to the number of dice (with buttons ranging from 1 to 7).

Notes:
- This could be a feature that users could enable or disable in their preferences.
- The ability to type in a different number would be retained, obviously, for unusual cases

**Comment by sIKE23** [comment]
Was testing this and it broke the automation for auto-ini......

**Comment by anandaguneratne** [comment]
I'll take a look.

**Comment by sIKE23** [comment]
Was working on getting some buttons working, and this code was still in, when I select a Dice Number it rolls the number of Dice selected -1.

**Comment by sIKE23** [comment]
I am thinking about adding a button that you double click on to roll the dice.

**Comment by anandaguneratne** [comment]
That's good. Definitely an improvement.

**Comment by sIKE23** [comment]
Also fixed the menu items roll now roll the proper number of dice and if the dialog box is canceled out of we no long roll the dice (changed if count == from None to 0)

**Comment by anandaguneratne** [comment]
I think this is entangled enough with #144 that we don't really need a separate issue.

**Comment by sIKE23** [comment]
Can we add Roll 0 dice or (just the effect dice) item to the menu?

**Comment by anandaguneratne** [comment]
We could, but it seems unnecessary. If all you care about is the effect die, it doesn't matter how many other dice you roll.

**Comment by sIKE23** [comment]
There are many times you want to just roll the Effect Die. (Defenses and Escape Rolls off the top of my head)
Add in a 'Roll Effect Die' button and its color should be #E0B525 so something like:

colors = [getActionColor(attackList[i]) for i in range(len(choices))] + ["#666699","#E0B525","#000000"]
choices.extend(['Other Attack Dice Amount','Roll Effect Die','Cancel Attack'])

Fix up the logic for inserting the Effect Die button and logic to rollDice(0) if selected. I almost have this figured out but don't understand the if/elif logic that follows....

**Comment by anandaguneratne** [comment]
Okay, sure. My point was that you can just roll X amount of dice and ignore everything but the effect die roll, but putting in a dedicated d12 button would make the menu look nicer, even if it is unnecessary.

**Comment by sIKE23** [comment]
Done, Great Work!
