### ISSUE TITLE
Improve Documentation on OCTGN's Targeting Feature

### ISSUE THREAD

**Issue by ACG8** [sIKE23/Mage-Wars#127]
Currently, the only documentation on OCTGN's targeting feature (shift + drag arrow) is located in the "OCTGN Apprentice Mode" document, which bills itself as an alternative game type for new players. Since many of the players who are just learning to play Mage Wars on Octgn are likely to be veteran players from real-world games (who may not think to check the Apprentice Mode document), this is not the appropriate place for this information. Furthermore, the information on targeting lacks some important information, namely how to get a targeting circle placed on a card. This doesn't matter now, but in the future, if we automate certain targeting-related actions (such as declaring attacks and attaching enchantments), this will cause a serious problem because OCTGN currently only recognizes a card as being in the .targetedBy list if there is a targeting arrow pointing to that target AND that target has a targeting circle on it. I propose the following changes to documentation:

1. Include targeting information in both the "How to Play Mage Wars on OCTGN" and "Keyboard Shortcut Mappings" documents.
2. Include more complete information on targeting, including how to delete a targeting arrow and how to make a targeting circle appear on a card. For future automation purposes, we should also make it clear that the targeting circle is necessary to be able to use advanced automation features (unless OCTGN fixes this so that the targeting arrow is sufficient to get a card listed in .targetedBy)

**Comment by lettucemode** [comment]
Does the OnTargetCardArrow event not work as expected?  https://github.com/kellyelton/OCTGN/blob/master/octgnFX/Octgn.Library/Scripting/GameEvents.xml

**Comment by sIKE23** [comment]
How about we add this as a menu item to the New Feature Menu?

**Comment by sIKE23** [comment]
Schwenkgott's thoughts on this....

![new feature menu](https://cloud.githubusercontent.com/assets/5695175/6673634/aacc0bca-cbe2-11e4-990b-1e16a65389f7.jpg)

I can see making the button text simpler, what about splitting Searchable Codex and Rulings/Clarifications into two buttons? Your thoughts?

**Comment by ACG8** [comment]
Sure, go ahead. Not really a new feature (targeting arrows/reticles), but definitely significantly more functional than it used to be.

**Comment by sIKE23** [comment]
This is already in the BC section on new features, closing this out.
