### ISSUE TITLE
Decrease time needed to start debug mode by autochoosing color

### ISSUE THREAD

**Issue by anandaguneratne** [sIKE23/Mage-Wars#128]
Currently, testing new code and debugging is relatively painless, but it could be made even smoother. In particular, testing a new iteration in code requires starting a new game each time to test. By removing some of the choices from debug mode, the time needed to start a game could be reduced, allowing testing to happen faster and speeding up development of new code. It is also annoying to have to keep selecting the same choices over and over again.

In particular, I recommend the following two changes:

1. Autochoose color in debug mode. A developer does not care what color he is, so this choice needlessly adds 1-2 seconds to startup time.
2. Autoload the last deck that was loaded instead of making the developer open up the deck load menu and manually select a deck.  If you want to change the deck, you still can. This will decrease start time by probably 2-4 seconds.

**Comment by anandaguneratne** [comment]
https://github.com/sIKE23/Mage-Wars/commit/88718ce37b2fad90fb0522aa2231bac74f2ce74a implements auto-choosing color. Quick-loading a deck will take a bit more work, and may not be possible with the available tools (but I am not ready to give up just yet).

**Comment by sIKE23** [comment]
I like this. Once we get the Q1 release finalized, I will fork the code and create a Q1-2015 fork and you can work in that.....

**Comment by anandaguneratne** [comment]
Okay. I assume for now I just work in the master branch, then?

**Comment by sIKE23** [comment]
Can you create your own fork off of master? That way I can Cherry-Pick over
into Master.......

**Comment by anandaguneratne** [comment]
Sure, I have done that.

**Comment by sIKE23** [comment]
The main reason for that, is that I want to push out a release very soon
but don't want to mush your inspired work, if you want you could name it
Q1-2015 and that way we can merge that into master once we release and run
bug free and freeze the 1.11.x.x code.....

**Comment by anandaguneratne** [comment]
Ah. Well, I already named it ACG's branch. Is it possible to change the name after creating the branch?

**Comment by sIKE23** [comment]
Easiest is to create a new branch off of the ACG's-Branch and name it what
you want and then delete the ACG's-Branch.....

//FC

**Comment by sIKE23** [comment]
anandaguneratne said:
>Quick-loading a deck will take a bit more work, and may not be possible with the available tools (but I am not ready to give up just yet).

Did the addition of the OS module make this feasible now? Do we want to split this issue in half and move the 2nd half to the Q2 Release?

**Comment by anandaguneratne** [comment]
The problem with quickloading is that I can't find a function that loads a deck (though the OS module will probably help once I can). The only current way I know how to interact with decks is through the load deck command built into OCTGN itself (that players use while actually playing the game). I have searched through the documentation, but there is no function that I can find that interacts with deck files.

**Comment by sIKE23** [comment]
So there is no way to implement the second half. Do we just want to go
ahead and close this issue, split it and close one and wontfix the other?

</sIKE>

**Comment by anandaguneratne** [comment]
Yeah, that sounds good.
