### ISSUE TITLE
flipcard() does not work on "Vine Snapper"

### ISSUE THREAD

**Issue by anandaguneratne** [sIKE23/Mage-Wars#130]
In the master branch:

If you attempt to execute flipmarker() on, for instance, a Vine Snapper, it will notify:
"{me} flips Vine Marker" and not do anything (in other words, it is not possible to flip Vine Snapper).

This is caused by actions.py lines 1368-1373, which read:
	if "Vine" in card.Name and card.controller == me:
		if card.alternate == "B":
			card.switchTo("")
		else:
			card.switchTo("B")
		notify("{} Flips Vine Marker.".format(me))

**Comment by sIKE23** [comment]
Fixed and Closing
