### ISSUE TITLE
Simplify code by replacing elif lists with dictionaries

### ISSUE THREAD

**Issue by anandaguneratne** [sIKE23/Mage-Wars#132]
Dictionaries are more elegant/concise and easier to read,modify, and expand than long elif lists. See https://github.com/sIKE23/Mage-Wars/commit/88718ce37b2fad90fb0522aa2231bac74f2ce74a for an example of how this can be implemented.

Benefits:
- Code takes up less space and is easier to read
- Easier to expand to include more cases

**Comment by sIKE23** [comment]
I like the Player Color code change.

**Comment by anandaguneratne** [comment]
Subsumed by https://github.com/sIKE23/Mage-Wars/issues/135; we don't need two separate issues.
