### ISSUE TITLE
Error raised when dice are rolled before deck is loaded

### ISSUE THREAD

**Issue by anandaguneratne** [sIKE23/Mage-Wars#133]
If you roll dice immediately upon entering the game, it raises an error:

line 314 in rollDice
NameError: global name 'dieCardX' is not defined

This is because dieCardX is only defined when a player's deck is loaded, via onLoadDeck()>AskDiceRollArea()>setDRAIP

**Comment by sIKE23** [comment]
Do you think we should just add a check in and if dieCardX  is Nul we prompt with please Load a Deck msg?

**Comment by anandaguneratne** [comment]
Yes, that would probably work. Though it would be nice to be able to roll dice before the game (I can't think up a reason, but I am sure somebody will want to at some point. Maybe some variant where you randomly determine your deck?)

**Comment by sIKE23** [comment]
We do have a coin flip for that......or did I take it out?

**Comment by sIKE23** [comment]
We can fix the bug, and next release look at re-examining how dice are handled. How does that sound?

**Comment by sIKE23** [comment]
Thinking that we can move the Dice Rolling Area location selection into the RollDice definition. This was the very first Python I learned. That is why it is so spaghetti like. 

So my only thought is that the first person to press F1 should get to make the choice?  Not sure of "when" during the game setup process we should do this......

**Comment by anandaguneratne** [comment]
Why do we offer a Dice Rolling Area location selection, anyway? Does anybody choose the area below the board? I always choose the one on the side, because there is so much more horizontal space than there is vertical space.

What if you autoset the dice roll area, and give players the option to change it if they want to? That way it can be set onGameLoad.

**Comment by sIKE23** [comment]
ACG,

This was a feature request from Schwenkgott and Charmyna. You can not make
it a setting Automation like setting that you check for because then
players can have different preferences and you will end up with both. I
like your suggestion but lets hold off until the 60% goal is met, lets hope
very soon! I want to change the dice roll graphic and add a "Next Phase"
button and all three of these items will be a customer card size.

//FC

**Comment by sIKE23** [comment]
Fixed and Closing
