### ISSUE TITLE
AttachCards alignment function may misorder cards in multiplayer games

### ISSUE THREAD

**Issue by anandaguneratne** [sIKE23/Mage-Wars#134]
Due to the way the attachCards alignment function works, if there are more than 2 players, it is possible to have an ordering of cards in which P2's cards are assigned indices that depend on P3's indices before P3's indices are assigned. For example, if the enchantment stack is (by card controller):

P1
P2
P3
P2

P1's card is assigned first, then P2's cards are assigned, but since P3's card has not yet been assigned, the card at the bottom of the stack may not be set to the correct index.

This does not by any means break the attachment module, but it can lead to desynchronization of card indices between players and some ugly, misordered attachment stacks, so it will need to be fixed.

**Comment by sIKE23** [comment]
Here is the bug to resolve for OCTGN.

https://github.com/kellyelton/OCTGN/issues/1348

**Comment by anandaguneratne** [comment]
That is a different bug than the one referenced in this issue; that bug deals with what happens when you group select and move a stack; this one deals with what happens when 3 or more players have cards attached to the same card.

**Comment by sIKE23** [comment]
Ok sorry about that if there is not an issue on this open it and please
correct my mistake, you know much better than I do....

//FC

**Comment by anandaguneratne** [comment]
Opened an issue here: https://github.com/sIKE23/Mage-Wars/issues/139

**Comment by anandaguneratne** [comment]
This issue should be fixed by this updated: https://github.com/sIKE23/Mage-Wars/commit/6d83d2a917a17a760182ab5f50279a8827f483a0
