### ISSUE TITLE
Simplify Repetitive Sections of Code

### ISSUE THREAD

**Issue by sIKE23** [sIKE23/Mage-Wars#135]
Something other than foo :+1:

**Comment by sIKE23** [comment]
Bumped into a bit of a delima with the card type for Phases and Diceroll from this commit:
c61718aa30c1df3d7840f64074fe61e9eda42ce8 I have a filter on Internal to prevent things from happening:
```python
def toggleAction(card, x=0, y=0):
	global mycolor
	mute()
	if card.Type == "Internal":
		return
```
Do I have to update this bunch of times or is there a simple way to do this now, and add new types in future in one place?

**Comment by anandaguneratne** [comment]
I'm not sure what you are asking. What is it that you want to update, exactly?

**Comment by sIKE23** [comment]
if card.Type == "Internal" or card.Type == "Phases" or card.Type == "Diceroll":

**Comment by sIKE23** [comment]
so what I am asking is can we make a group (list?) (dictionary?) of card.Type and then use that group as the test? That way if I add more non-game relevant card.Types I can just add them into the group once....

**Comment by anandaguneratne** [comment]
Okay, if I understand your correctly, you want to know if there is some way to define a set of types such that you can simply add more types to the list rather than having to add a separate <if Card.type == Foo : return>?

Yes, you can. Try:
<typeIgnoreList = ['Internal','Phases','Diceroll']>

and then, for this particular function:
<if card.Type in typeIgnoreList: return>

Is this what you are looking for?

**Comment by sIKE23** [comment]
would this work?

	if card.Type in typeIgnoreList or not card.isFaceUp: return

**Comment by anandaguneratne** [comment]
Yeah, that should work, but you don't have to define typeIgnoreList inside each function. Just make one typeIgnoreList outside all of the functions, and they will recognize it as a definition.

I meant to get around to making a function generator for the token toggle functions; that would reduce the maintenance a lot.

**Comment by sIKE23** [comment]
I think this work is done for the Q1 release, let me know if one should be opened for Q2.
