### ISSUE TITLE
Dragging a stack of attached cards causes them to reattach to each other

### ISSUE THREAD

**Issue by ACG8** [sIKE23/Mage-Wars#139]
If you select a card and multiple attached cards (by dragging a box around them), dragging the stack will cause the attached cards to detach and re-attach to each other.

See https://github.com/kellyelton/OCTGN/issues/1348

**Comment by sIKE23** [comment]
Where are we on this issue?

**Comment by anandaguneratne** [comment]
Still unsolved. I took a look at it a while after the OCTGN update, but didn't make much progress; I can take another look at it now.

**Comment by anandaguneratne** [comment]
Fixed now with the above commit, at least as far as I can tell.
