### ISSUE TITLE
Refining attachment restrictions - Q1-2015

### ISSUE THREAD

**Issue by anandaguneratne** [sIKE23/Mage-Wars#140]
Right now, the standards for what can be attached to what are pretty loose; certain conjurations, all enchantments, and all equipment can be attached to just about everything, and pretty much anything can be attached to spellbind, familiar, spawnpoint, and mage-stats cards (to allow players to indicate which spells are prepared or what equipment is attached to their mage). Refining these restrictions is pretty easy, since there is a dedicated canAttach() function, but there are a lot of cases to cover.

1: Is this something we want to improve before the end-of-year release? Or can it wait until Q1-2015?
2: How far do we want to take the restrictions? For instance, should we prevent the attachment of, say, Eagle Wings to a mage, or just go as far as preventing the attachment of a zone-targeted enchantment to a creature? Should we even have restrictions at all? Or should enchantment restrictions be an option that players can toggle?

**Comment by sIKE23** [comment]
Good questions! I would think that we can do this for Q1-2015. I would like to see Spellbind tackled first, and then if we can come up with a generic way (maybe a dictionary of "Types of Targets") to enforce targeting I think that would be cool, but yes it can be a rabbit hole if we let it be......lets start small and build from there.

**Comment by sIKE23** [comment]
First thing I think I would like to see is when you attach a facedown enchantment to a card it triggers the castspell function for the Enchantment and prompts the player to pay the two mana.....

**Comment by sIKE23** [comment]
Also you shouldn't be able to attach to a Facedown card, which should be easy to add in the a card.isFaceUp

**Comment by sIKE23** [comment]
We need a menu item detach card if feasible and reasonable....

**Comment by anandaguneratne** [comment]
Sure. I'll look into those.

**Comment by anandaguneratne** [comment]
Two down, one to go. Though I am not certain that the menu detach card item is necessary - simply clicking and dragging is enough to detach a card, so who would go to the trouble of pressing a shortcut key? Regardless, the option is there now.

**Comment by sIKE23** [comment]
There is a function that is called castSpell that you might want to look at to integrate this code with, it is the part that calls the discounts.

**Comment by anandaguneratne** [comment]
Yes, I considered that (and based the code off of it); I'll see if I can combine the two, then.

**Comment by anandaguneratne** [comment]
I see what he's done; he's defined a dictionary for each card with all the relevant information for that card (including, if I'm not mistaken, specific functions to call). I did something similar when defining monsters, items, and spells for Mage Wars RL. It would probably simplify many of our functions and possibly speed up parts of the code, but I don't think the gains would justify the amount of time it would take to build and maintain (for each new set). Besides which, we already have much of the data that we need in the card xml files, and our system is already designed around parsing the raw text of the cards, so I don't think I want to make the switch. Do you know why he disliked the canAttach function in particular? Is it just the sheer number of *or* statements?

Once functionality is in place, I do intend to work on making the code shorter, faster, and more elegant, though.

**Comment by sIKE23** [comment]
I would like to see Spellbind object enforcement. i.e. Elemental Wand non-Epic attack spell, Helm of Command, non-Epic command incantation, Mage Wand non-Epic incantation, Thoughtspore non-Epic Level 1-2 attack or incantation spell, and my favorite Wizard's Tower non-Epic quick attack spell.

In-conjunction see my query over on #151

**Comment by anandaguneratne** [comment]
That (enforcement of spellbind/familiar/spawnpoint restrictions) has already been implemented. See attachCards.py lines 241 - 264.

**Comment by sIKE23** [comment]
Awesomeness! Close this out then?

**Comment by anandaguneratne** [comment]
Sure. There might be more restrictions we want to enforce in the future, but I think this is good for now.

**Comment by sIKE23** [comment]
Here is my thoughts on revealed spellbind objects....offset is -27

![spellbind objects](https://cloud.githubusercontent.com/assets/5695175/6159038/22b1a05a-b216-11e4-9e6e-ab193f0e5669.jpg)
