### ISSUE TITLE
Manual Reset followed by loading a deck triggers another reset

### ISSUE THREAD

**Issue by ACG8** [sIKE23/Mage-Wars#142]
If you first manually reset the game and then load a deck, you get the message "{} has attempted to load a second spellbook, the game will be reset", and then the game is reset again.

Obviously not high priority, but also obviously a bug.

**Comment by sIKE23** [comment]
I was looking at this last night when my brain got tired. This should be one of the items fixed in the #141 category.

**Comment by sIKE23** [comment]
This is fixed
