### ISSUE TITLE
Use initiative token as a button to advance to next phase.

### ISSUE THREAD

**Issue by ACG8** [sIKE23/Mage-Wars#143]
Currently, the initiative token does not do anything if you double click on it. Why not turn it into a button that signals you are ready for the next phase? (like ctrl+down) I suppose the sign that indicates the current phase might make more sense, but the initiative token looks more like a button.

**Comment by sIKE23** [comment]
Interesting idea, the question is since this changes from Round to Round will it still work as we want it to? If this doesn't work out I was going to create a button to advance to the next phase.

**Comment by sIKE23** [comment]
It will work as long as the GUID on the marker stays the same. What about to phase marker(s) instead of the initiative marker(s)?

**Comment by sIKE23** [comment]
Or we can do both :)

**Comment by sIKE23** [comment]
Done
