### ISSUE TITLE
Switch Dice Roll Shortcut to <TAB>?

### ISSUE THREAD

**Issue by anandaguneratne** [sIKE23/Mage-Wars#145]
Currently, the Dice Roll shortcut is set to <F1>. Since dice rolling is perhaps the most common thing players will need a shortcut for, we want it to be an easy one. F1 is a small key, and on some computers (like mine) requires an additional <fn> keypress. The <TAB> key is significantly larger, more conveniently positioned (the left hand ring finger has no trouble finding it), and easier for new players to learn/remember since it is unique. What do you think of making this change? Existing players would have to readapt (and might grumble a bit), but it wouldn't take them long.

Another possibility is SPACE, but that might be going too far.

**Comment by anandaguneratne** [comment]
Also, I am using TAB for the new targeted attack rolls. I don't know if you can use the same shortcut for two actions (though they are different types whose menus do not overlap), but if so that would be really cool; TAB when hovering over the table for a generic dice menu and TAB when hovering over a creature for a targeted dice menu.

**Comment by sIKE23** [comment]
When you don't have you pointer over a card Tab tabs through Game, Game Documetns, Options, Etc menu.....

**Comment by sIKE23** [comment]
I have tried in the past to just use Unshifted Keys with no luck, like I wanted next Phase to be "Enter" but that didn't work out :(

**Comment by sIKE23** [comment]
How is this going to work with the proposed Roll Dice button?

**Comment by anandaguneratne** [comment]
Try out the my latest commit and see; TAB works unshifted (I don't know about other keys, though).

I don't think this changes the roll DIce button at all - that is basically just a generic roll dice, rather than a targeted one.

**Comment by anandaguneratne** [comment]
https://github.com/sIKE23/Mage-Wars/commit/63276a86f5c202a83266b18125cab0bbc8e15912 implements TAB as the all purpose dice rolling key. It turns out you can indeed have the same hotkey mapped to both a group action and a card action. Even better, the card action takes precedence. So if you press TAB while your cursor is hovering over a card, you get the attack menu for that specific card, whereas if you press it while your cursor is over nothing in particular, you get the general attack menu. Try it out and let me know what you think; personally, I think TAB works much better than F1.

**Comment by sIKE23** [comment]
Can we leave F1 as on option and make both work the same, some people have been playing for over 2 year and they may not be too happy. I am not asking if it is possible look at Next Phase, both CTRL+Down Arrow and CTRL+Enter change to the next phase.
