### ISSUE TITLE
Add Ranged +1 Markers

### ISSUE THREAD

**Issue by ACG8** [sIKE23/Mage-Wars#148]
There are Melee +1 markers, but no Ranged +1 markers, even though the latter exist in real life. Would be nice to have.

**Comment by anandaguneratne** [comment]
Nice. But can we call them "Ranged +1" as opposed to "Range +1"? That way we are less likely to get confused later, since "Ranged" is how MW refers to the trait.

**Comment by sIKE23** [comment]
Should I create a Card Menu Item with a Keyboard Shortcut for this marker?

**Comment by anandaguneratne** [comment]
Yes, probably.

**Comment by sIKE23** [comment]
Complete
