### ISSUE TITLE
Add logic to Automate Upkeep for Mana Prism

### ISSUE THREAD

**Issue by sIKE23** [sIKE23/Mage-Wars#153]

**Comment by anandaguneratne** [comment]
This is more of an XML thing than anything else, but isn't it "Mana Siphon"?

**Comment by sIKE23** [comment]
But it snags Upkeep costs .......

**Comment by anandaguneratne** [comment]
I don't understand. Do you mean that 'Siphon' is currently used as a tag in some function that evaluates upkeep costs?

**Comment by sIKE23** [comment]
Changed to Mana Prism ...that's the one I was thinking about....

**Comment by sIKE23** [comment]
So I am trying to capture all of the cards that meet the requirements for this card.

Mordok's Obelisk, Suppression Orb, Harshforge Monolith 

Any other cards you can think of?

**Comment by ACG8** [comment]
Mana Siphon, Armor Ward, Essence Drain, Enchanter's Wardstone, Suppression Cloak, Drain Power, Mana Leech, Staff of the Arcanum

**Comment by sIKE23** [comment]
Just realized I am doing Essence Drain wrong....

**Comment by sIKE23** [comment]
Armor Ward - During the Spellcast sequence
Drain Power - During the Spellcast sequence
Essence Drain - Calculated during Upkeep Phase
Enchanter's Wardstone - During the Spellcast sequence
Mana Siphon - Don't think this applies as it is not a Drain or Transfer
effect, changes the Channeling Stat....
Mana Leech - During an Attack Sequence
Suppression Cloak - During an Attack Sequence
Staff of the Arcanum - During an Attack Sequence

So from an Upkeep POV Essence Drain is the only one that I need to concern
my self with for the task at hand.

//FC

**Comment by sIKE23** [comment]
Sorry for throwing so much at you today, no rush but I can not figure out
why this snippet:

if card.Name == "Essence Drain" and isAttached(card) == True:# handle
Essence Drain
  attachedToCard = getAttachTarget(card)
  if attachedToCard.controller == me:
      TraitValue, TraitStr = getTextTraitValue(card, "Upkeep")
      EssenceDrain = 1

is throwing me this error message:

[image: Inline image 1]

I have pushed this up in to Github....

Thanks!

//FC

**Comment by ACG8** [comment]
The problem is in your getTextTraitValue() function.

Specifically, you are calling int('2]'), which is invalid because of the right bracket.

The reason it is '2]' rather than '2' is because the line 

STraitCost = strTrait.split("+")

is being applied to the string "[Upkeep +2]"

Which means STraitCost = \["[Upkeep ","2]"\]

To fix this, just use the str.strip method or the str.replace method:

example:

	if STraitCost[1].strip('[]') == "X":
		infostr = "The spell {} has an Upkeep value of 'X' what is the value of X?".format(card.Name)
		TraitCost = askInteger(infostr, 3)
	else:
		TraitCost = int(STraitCost[1].strip('[]'))

**Comment by sIKE23** [comment]
It is now working, but I have a flow issue of when you add the Marker to the Prism and when you pay the Upkeep. Right now adding the Marker is done before paying the Upkeep. Should be the other way around. I will have to chew on it a bit to work out all of the details.
