### ISSUE TITLE
AutoRollInitiative takes a long time

### ISSUE THREAD

**Issue by ACG8** [sIKE23/Mage-Wars#155]
Maybe there are reasons why this can't be fixed, but in debug mode (and possibly in multiplayer, though I haven't tried it yet), autoRollInitiative takes a noticeably long time to resolve (there is a significant pause). Is there any way to reduce this time?

**Comment by sIKE23** [comment]
Honestly this was bolted onto the script. I have been looking at it, but it digs over into multiplayer support which I am afraid of breaking. I will study it a bit here soon and see why it takes so long.

**Comment by sIKE23** [comment]
I think somewhere along the way with one of your early changes you have broken auto-initiative for single players. I am working on getting all of this re-worked but I think it will end up being a Q2 item.

**Comment by sIKE23** [comment]
This is fixed, correct?

**Comment by ACG8** [comment]
I think so, yes.
