### ISSUE TITLE
Game ignoring group and card actions

### ISSUE THREAD

**Issue by anandaguneratne** [sIKE23/Mage-Wars#156]
Something is wrong. I can't roll dice at all, even by right clicking and selecting the option. It won't even register the fact that I called the rollDice function (I added a debug line just to see). Could one of your most recent changes have caused this? Let me know if you are having the same problem.

**Comment by anandaguneratne** [comment]
Actually, it is not just the dice. None of the actions are working; clicking on any group or card action has no effect, even though they still appear on the menu.

**Comment by sIKE23** [comment]
Interesting it works when you are in dev mode "OCTGN.exe -x" which is how I was testing last night. I am looking in to why it does not work in std mode.

**Comment by sIKE23** [comment]
https://github.com/kellyelton/OCTGN/issues/1359

**Comment by sIKE23** [comment]
Just so you aware these are not working as expected. Both players create the items at this point. I am working on getting this working properly but the spaghetti is in a big bowl. I have been breaking out each of these functions (you will never see this) into its own py file as I chase through the calls to the functions. If your not aware, python global variables should be used sparingly as the game can wipe them out at any point, read, always during a disconnect/reconnect, if their persistence is not important then they are ok to use. If it important use the OCTGN based GlobalVariables.

**Comment by sIKE23** [comment]
This was fixed in one of the very recent OCTGN updates...closing
