### ISSUE TITLE
Attachment Discard Bug

### ISSUE THREAD

**Issue by sIKE23** [sIKE23/Mage-Wars#157]
From Schwenkgott:

Situation; Tanglevine is attached to a creature. Tanglevine is destroyed and the Owner uses "del" on Tanglevine to move it to discard. The Tanglevine card vanishes as i should be, but reappears right after that and self attached so an other (random?) card of the same Player. 

After that, there seem to be some difficulties to delete the card again. Tanglevine has to be detached from this new card first in order to discard it finally.

**Comment by sIKE23** [comment]
Can I get you to fix this one the Master fork? I will go ahead and put another release with this fix and one other minor one while I am at it. I would normally cherry pick this over, but this is such a large difference now, I am not sure what or if would break anything on that side.

**Comment by anandaguneratne** [comment]
Pretty sure this is fixed.

**Comment by sIKE23** [comment]
We never opened up a Issue for Binding, but we have the same issue with Binding that we had here with Attachments. We need to update the BindDict when a card is deleted/dragged/cast and moved from the Bound to object.
