### ISSUE TITLE
Incorrect card image for Staff of the Arcanum

### ISSUE THREAD

**Issue by anandaguneratne** [sIKE23/Mage-Wars#160]
The card image used for 'Staff of the Arcanum' has the mana drain traits displayed as 'Mana Drain 1' rather than 'Mana Drain +1'. The most recent official version of the card corrects this error. This is also reflected in the XML, but I will be fixing this with my next commit.

**Comment by sIKE23** [comment]
I just checked the o8c file on the dropbox share and the Staff of the Arcanum shows the Mana Drain +1 trait.

**Comment by anandaguneratne** [comment]
Okay... maybe it is just my computer, then? Actually, I have suspected for a while that I am not receiving updates to the card images, since many of my cards (including the FiF cards) are shown as proxies. Any idea why this might be?

**Comment by sIKE23** [comment]
You have to load in the new Card Images:

http://octgn.gamersjudgement.com/wordpress/magewars/install-2/imagepacks/

//FC

**Comment by anandaguneratne** [comment]
Thanks. I downloaded the images, and everything is displaying correctly now.
