### ISSUE TITLE
Rework cards with new card size features

### ISSUE THREAD

**Issue by ACG8** [sIKE23/Mage-Wars#161]
Images for objects that are not sized the same way as standard cards (ex. the initiative token, vine markers, the phase sign, and sideways wall) are distorted to the dimensions of standard cards. I think this might be a result of the new OCTGN update, since I noticed it right after installing that. Let me know if you are seeing the same thing.

**Comment by sIKE23** [comment]
This is due to the new card size feature, I am still working on how to resolve....
