### ISSUE TITLE
Searchable E-Codex

### ISSUE THREAD

**Issue by ACG8** [sIKE23/Mage-Wars#171]
This is somewhat related to #165. Mage wars players, and especially newer players, often have trouble remembering exactly what a particular trait does. It would be easy (though slightly time consuming, although COPY+PASTE will speed things up a lot) to make a dictionary containing information on the exact rules, along with rule clarifications, for each trait that can be searched by players.

Interface-wise, I am thinking a group action (perhaps with ? or CTRL+SHIFT+?) that brings up an askString menu. We parse the entry to standardize the cases used (so melee +X -> Melee +X) and anticipate common variations (Melee+X -> Melee +X), and then feed it to the dictionary, returning the resulting entry to the player, possibly as a single-button menu (just for legibility; whisper is not ideal for this sort of thing).

This would be of tremendous help, both for resolving rules disputes over obscure side-cases as well as helping newbies learn the rules of the game.

**Comment by anandaguneratne** [comment]
Incidentally, I would like to be in charge of these projects (#165 and #171)

**Comment by sIKE23** [comment]
That's not surprising that you want to take the lead. I already provide
access to the codex and have thought about doing the same with the FAQ.
These would/are images though so not searchable.

The only thing to consider is we have a maximum package size of 9MB and we
are pushing a package size of almost 7MB already. Someone along the way
asked for some more sounds to be included and all markers live in the
GameDatabase directory so we have to plan for future growth.

</sIKE>
