### ISSUE TITLE
Double Click Rotation?

### ISSUE THREAD

**Issue by ACG8** [sIKE23/Mage-Wars#180]
I had an idea. What if double clicking on one of the top corners of a card rotates it in that direction (i.e. left corner rotates counterclockwise, right corner rotates clockwise). This would let us eliminate the rotate command, and would be easier for players.

**Comment by sIKE23** [comment]
I like the idea, so what would happen if the "top" of the card is rotated
180 degrees? I think the right click and Rotate should stay also....

**Comment by ACG8** [comment]
Not sure. I'll have to test it and figure out exactly how rotation affects it. I don't think it will be too hard to do, though. I'll experiment later today or tomorrow morning.

And I can see the argument for keeping rotation as a function too. We can have both!

**Comment by ACG8** [comment]
Sadly, it doesn't look like we can do this at the moment. There appears to be no way to get the mouse cursor position. I assumed that the (x=0,y=0) at the start of each card function were providing the coordinates of the mouse, but they appear to have no purpose whatsoever.

**Comment by sIKE23** [comment]
The X,Y are board coordinates....

**Comment by ACG8** [comment]
But for what? They generally aren't used in the functions, and the functions work just fine without them.

**Comment by sIKE23** [comment]
I don't know but I will ask...
