### ISSUE TITLE
Improve castSpell function

### ISSUE THREAD

**Issue by sIKE23** [sIKE23/Mage-Wars#188]
ACG says
> The castSpell function seems rather complicated to me. Do you mind if I look into simplifying/improving it?

sIKE says
> Sure

**Comment by ACG8** [comment]
Just a heads-up; I've decided to do this for Q1. There isn't actually that much to do. It will take a little while, but there are other issues we need to fix before the alpha release anyway.

**Comment by sIKE23** [comment]
Spellbind costs are not being calculated.......

**Comment by sIKE23** [comment]
The caster of the spell is not correct here....
![new jpeg image 2](https://cloud.githubusercontent.com/assets/5695175/6673757/915a3a76-cbe3-11e4-97c9-361c35859ea3.jpg)

I paid the 5 mana but I was not the Forcemaster.....

**Comment by ACG8** [comment]
Without more context, I'm not sure I can diagnose the problem.

**Comment by sIKE23** [comment]
I cast the Wall of Thorns and paid for it, and got:

Forcemaster conjures Wall of Thorns!

My opponent was the Forcemaster and I was playing the Wizard.

**Comment by ACG8** [comment]
Pretty sure I know what the problem is, then; I'll see about fixing it.

**Comment by sIKE23** [comment]
Druid Leaf Ring is giving its Discount bonus to a Spawnpoint, it should only help a Mage's casting cost.
