### ISSUE TITLE
Automate Placement of Crush Tokens on Stranglevine and its Upkeep

### ISSUE THREAD

**Issue by sIKE23** [sIKE23/Mage-Wars#190]
Had to automate the Stranglevine for Upkeep and this was the logical location and time to place the Crush Token.

**Comment by sIKE23** [comment]
Your good with death/damage message, need a cool one for when Stranglevine applies its damage, and good ideas?

**Comment by ACG8** [comment]
Hmm...

"Stranglevine tightens its hold on {}! ({} damage)"

"As Stranglevine grows, its hold on {} tightens! ({} damage)"

"{} is constricted by Stranglevine! ({} damage)"

"Stranglevine crushes {}! ({} damage)"

"Stranglevine writhes and constricts! ({} damage)

Don't think it needs to be much fancier than that.

**Comment by sIKE23** [comment]
Wow, that was fast and I really like them. Could you add that in, I just
mage a commit with where that would need to go. Along with applying the
damage.
