### ISSUE TITLE
Remove TAB-Targeted Attacks?

### ISSUE THREAD

**Issue by ACG8** [sIKE23/Mage-Wars#194]
Now that attacks can be easily declared using arrows, I think it might be a good idea to remove the option to declare attacks with TAB and a targeting reticle. TAB would still be used for dice rolls, of course, and I think it could be repurposed for untargeted abilities, but it is clunkier than using an arrow when it comes to declaring attacks. Deleting it will also reduce maintenance. Thoughts?

**Comment by sIKE23** [comment]
I agree the Tab should just a generic roll dice feature mainly for those
who turn off the BC.

**Comment by ACG8** [comment]
Right. I will remove the attack code from that. I might also add code for activating creature special abilities (such as necropian vampiress flying ability) using TAB; do you think it would work well as the key for that, or would it be too confusing given the tableAction use for TAB?

**Comment by sIKE23** [comment]
Are talking about things like Bim-Shala? Might move the dice roll back to
only F1 and have Tab be the Special Actions key?

**Comment by ACG8** [comment]
Well, TAB is very convenient when you just need to roll dice. And F1 is a really inconvenient key; if we could use SPACE, that would be much better. Is there perhaps another key suited to special abilities?

Don't think Bim-Shalla will be implemented until Q2; this is mostly for simple things like Necropian Vampiress, Blue Gremlin, etc. that do not require declaring a target for the ability.

**Comment by sIKE23** [comment]
I am not going to mess with your baby, as for another appropriate key I am
not sure. Ctrl + Tab maybe?

**Comment by ACG8** [comment]
I don't know, I feel like it should be just one key...why don't we use TAB for now, and see if anybody reports confusion.

**Comment by sIKE23** [comment]
This is done and working as expected!
