### ISSUE TITLE
Reported Bug: Chat text not visible

### ISSUE THREAD

**Issue by ACG8** [sIKE23/Mage-Wars#197]
Imaginator reports the following problem:

"Lately I've sometimes encountered a bug where I lose the ability to see any new text in the chat box at a certain point in the game. I can still enter text but I can't see what I type. I've had to open separate private message windows to communicate with my opponent. The game I just finished was really awesome and I want to keep the gamelog, but I can't because I can't access the rest of the gamelog since most of it never appeared for me on my end. Everyone else could see it. But I couldn't. And none of the spectators were present for the whole game. So there is part of the gamelog that I am missing. I wonder if the problem is with the gamelog/chatbox's scroll bar, but I honestly have no idea.

Could you look into this sometime this weekend if possible so I can maybe recover my gamelog?

Thank you!"

**Comment by sIKE23** [comment]
The game log is lost. At some point what I like to do, and this was
something lettucemode wanted to do :( was to capture the game stats to a
stats server, he even got a webpost (
https://github.com/kellyelton/OCTGN/issues/1277) added as a feature to
implement this. One thought is to:

def chatmsg(str):
    notify("{}".format(str))
    <add str to (what type of?) variable>

def privatechatmsg(str):
    whisper("{}".format(str))
    <add str to (what type of?) variable>

def debug(str):
    global debugMode
    if debugMode:
        whisper("Debug Msg: {}".format(str))
        <add str to (what type of?) variable>

Then provide a way to export this or copy it to the clipboard......

Long term I would like to log all of this to a stats server.

</sIKE>

**Comment by sIKE23** [comment]
Closing - #198 will fix this long term
