### ISSUE TITLE
Creature placement not working when laying out the map

### ISSUE THREAD

**Issue by sIKE23** [sIKE23/Mage-Wars#199]

**Comment by sIKE23** [comment]
I think that the latest work is much closer. I wonder if you are seeing what I am seeing?

Here is a pic:
![map-issue-1](https://cloud.githubusercontent.com/assets/5695175/8174053/9abd4496-13a5-11e5-8a14-3f6327fdcd42.jpg)
I count 14 Sslaks!

Here is chat log:
sIKE23 loads Ancient Wards (2 Players).
Debug Msg: a4b3bb92-b597-441e-b2eb-d18ef6b8cc77
Debug Msg: Secret Passage
Debug Msg: a4b3bb92-b597-441e-b2eb-d18ef6b8cc77
Debug Msg: Secret Passage
Debug Msg: bf217fd3-18c0-4b61-a33a-117167533f3d
Debug Msg: Sslak, Orb Guardian
Debug Msg: bf217fd3-18c0-4b61-a33a-117167533f3d
Debug Msg: Sslak, Orb Guardian
Debug Msg: bf217fd3-18c0-4b61-a33a-117167533f3d
Debug Msg: Sslak, Orb Guardian
Debug Msg: bf217fd3-18c0-4b61-a33a-117167533f3d
Debug Msg: Sslak, Orb Guardian
Debug Msg: bf217fd3-18c0-4b61-a33a-117167533f3d
Debug Msg: Sslak, Orb Guardian
Debug Msg: bf217fd3-18c0-4b61-a33a-117167533f3d
Debug Msg: Sslak, Orb Guardian
Debug Msg: 3d339a9d-8804-4afa-9bd5-1cabb1bebc9f
Debug Msg: V'Tar Orb Off
Debug Msg: 3d339a9d-8804-4afa-9bd5-1cabb1bebc9f
Debug Msg: V'Tar Orb Off
Debug Msg: 3d339a9d-8804-4afa-9bd5-1cabb1bebc9f
Debug Msg: V'Tar Orb Off
Debug Msg: 3d339a9d-8804-4afa-9bd5-1cabb1bebc9f
Debug Msg: V'Tar Orb Off
Debug Msg: 3d339a9d-8804-4afa-9bd5-1cabb1bebc9f
Debug Msg: V'Tar Orb Off
Debug Msg: 3d339a9d-8804-4afa-9bd5-1cabb1bebc9f
Debug Msg: V'Tar Orb Off

Looks like to me in zones where V'Tar Orbs are placed, the code is generating an extra Sslak, additionally the Orb and Secret Passage markers are being centered on the Sslaks. 

I am going to adjust the size of the SPT "marker" on the card and maker it much larger than it is today. Do you think I should do that to the other Domination "markers" as card? Once I have this done for the SPT the will need to be a little more work done on getting it centered.

**Comment by ACG8** [comment]
I think large markers are a good idea. Things in OCTGN are pretty small as it is; best to make sure players can see everything.

**Comment by sIKE23** [comment]
This is working great now! Closing this out!
