### ISSUE TITLE
Resolve Inconsistent Markers error message during Upkeep

### ISSUE THREAD

**Issue by sIKE23** [sIKE23/Mage-Wars#208]
@ACG8

**Comment by sIKE23** [comment]
@ACG8 
Have you seen anymore of these error messages since I made these updates?

**Comment by ACG8** [comment]
No. I haven't been testing for them, though.

**Comment by sIKE23** [comment]
They pop as error messages, so hopefully you haven't been seeing any, but
you have to advance through the phases to trigger the error.

**Comment by sIKE23** [comment]
Fixed
