### ISSUE TITLE
Mage Wars Arena and Academy

### ISSUE THREAD

**Issue by sIKE23** [sIKE23/Mage-Wars#220]
So I see a bit of a challenge with how to handle these two games. On one hand they are separate games but on the other hand the cards (and therefore logic and associated game logic) will be (mostly?) forward compatible from Academy to Arena.

With this in mind I have been trying to work out in my mind at least how we should handle both games.

First question are both of you @ACG8 and @Kharhaz interesting in being devs on the Academy side?

The next thoughts are more free form and what I got from my ongoing attempt at the Academy module. 

* We should try to keep code that is cross compatible between the games as much as possible
* That means we will need to think about on how we should handle code that is not useful for both Academy and Arena, my thoughts are these include OnTableLoad, OnGameStart, OnDeckLoad(maybe), how initiative is handled, phases/turns/reset(maybe?)
* Brine recommends that the games (if they are different OCTGN game modules) have different GUIDs for the set data which means when we fix a single set data issue on one side we have to do it on the other side (at least for the Academy cards)
* With the above thoughts in mind:

1. Common to both games
   * common.py
   * attacks.py
   * textfunctions.py
   * attachcards.py  $$
2. Academy only
   * academy.py
3. Arena only
   * arena.py

$$ - will this work? canAttach and canBind are the only functions that I am not sure about. Maybe in each respective game.py file we setGlobalVariable("GameType", "Arena" or "Academy") and then code in common, attacks and attachcards could have an if on "GameType" if need be?

This leaves the other biggie I have in mind, the SpellDictionary, how do we handle that with both games?

Other thoughts and input on these topics are highly desired by me.....

**Comment by ACG8** [comment]
> First question are both of you @ACG8 and @Kharhaz interesting in being devs on the Academy side?

Well, at the moment I have enough to do just working on arena, (have been extremely busy, so I haven't had time to code much lately, but I will be getting back to it soon) so I am not sure how much time I would have to spend on Academy. So as an "offical" dev, no. But as you point out, much of the arena code can be ported over to Academy. Which brings me to:

>$$ - will this work? canAttach and canBind are the only functions that I am not sure about. Maybe in each respective game.py file we setGlobalVariable("GameType", "Arena" or "Academy") and then code in common, attacks and attachcards could have an if on "GameType" if need be?

>This leaves the other biggie I have in mind, the SpellDictionary, how do we handle that with both games?

The SpellDictionary will vastly change the way the code works, including canAttach and canBind. It will let us put all of the card-specific functions in the cards themselves, which means the general code will become much more general. This should greatly facilitate porting the code to academy, as you can just define card specific stuff in the spelldictionary for academy. The only thing we need to worry about for Academy is differences in core mechanics, but it seems like the game devs are moving toward making Academy more and more like arena (for instance, the switch to the alternating actions system), so we should probably wait to see exactly how different the core mechanics end up being.

Of course, I have to write it first, and until I have, you will obviously not be able to begin porting it; I hope this is not too much of a bottleneck...

**Comment by sIKE23** [comment]
From Brine on IRC:

>[19:53] <brine> ok i'm back on my comp to type all this out
>[19:54] <brine> so when OCTGN looks up a GUID into the database, and it finds a match, it assumes that card belongs to the game
>[19:54] <brine> so if it looks up the GUID and the first one it finds is a duplicated one from another game, it could potentially screw up the card processing

Was really hoping to be able to share the set.xml data between the two games. Ick! This means double card images and set.xml. Maybe a script that takes the set.xml data from one and generates and GUID and replaces the GUID from the Arena set with the one for the Academy set.

**Comment by sIKE23** [comment]
Part I understand! See Part 2 below

Part 2 - the way I see things from Academy v. Arena POV is that you will do your work in Arena and I will pull it over into Academy. I will create the set data, then you will generate the spell dictionary from it. Once we are happy with that, I will have a script that replaces the GUID in both the set.xml and the Spell Dictionary and copies the image files to the Academy GUIDs.

The main thing is as we get started on the 2.x release we need to separate actions.py into to common.py and arena.py. If that is what we think will work best?

**Comment by sIKE23** [comment]
In reality can change anything and everything up that we want this time around (other than set.xml data and images)

**Comment by ACG8** [comment]
>The main thing is as we get started on the 2.x release we need to separate actions.py into to common.py and arena.py. If that is what we think will work best?

Sounds like a plan. I also need to finish up the code for Domination maps; where should I work on that?

**Comment by sIKE23** [comment]
I think that Domination would be an Arena only thing, so pull over into a
new arena arena.py on master? or should I fork master to a Domination
release? yeah this is gonna be fun...

**Comment by ACG8** [comment]
Well, domination will be released before v 2.x, right?

Maybe we could make a domination.py file. Then it would be easy to move the domination stuff over to the 2.x branch.

**Comment by sIKE23** [comment]
I like that....

**Comment by sIKE23** [comment]
The new game setup configuration will allow us to support Academy in the Mage Wars Arena module. My plan is to split out Arena specific functions, phase management as an example, into Arena.py file and create a Academy.py and put its game specific functions in it. Functions that are shared will go in to, I was thinking common.py, but main.py would work for my but it is not clear to me if you are planning on (generally) keeping the files split up the same way you have them now, with attachment.py and attacks.py as their own files.

**Comment by ACG8** [comment]
I think attachment.py and attacks.py should probably be consolidated into
main.py eventually (we could also call it common.py). They were split off
because they were new features with considerable complexity, but now they
are fairly ingrained into the rest of the program.

**Comment by ACG8** [comment]
Right... it might be worth finding ways to split them up.

One thing that occurs to me is that the Actions.py file currently contains
a lot of functions that are not actions. What if we put all of the actions
into Actions.py, and all of the events (like onLoadDeck) into Events.py?
Then the rest of the code could go into common/main.py.

**Comment by sIKE23** [comment]
You know, when I was doing the standalone version of Academy, this is
exactly what I did, I had events, constants, academy, attachments, attacks,
and common py files.

I find it easier to merge with smaller discrete files than one monsters
file that we both are working on at the same time.

//FC

**Comment by sIKE23** [comment]
Closing
