### ISSUE TITLE
Mage default location not working for Domination Maps

### ISSUE THREAD

**Issue by ACG8** [sIKE23/Mage-Wars#231]
The code that assigns each mage a default location for his or her cards when moved to the table appears to not be working for domination maps.

**Comment by sIKE23** [comment]
I think that this is the last code related item before we beta this code for release.

**Comment by sIKE23** [comment]
On the Wartorn Expanse (3 Players) map Player 1 is being setup in zone 1,4 instead of 1,3. The mapDict placement for the Mage seems correct to me too.

**Comment by sIKE23** [comment]
Here is what I am getting in the chat log

> Debug Msg: True
> Debug Msg: 1 0,-500
> sIKE23 prepares a Spell from their Spellbook by placing a card face down on the table.
> Debug Msg: True
> Debug Msg: 1 0,-500
>  sIKE23 prepares a Spell from their Spellbook by placing a card face down on the table.

**Comment by sIKE23** [comment]
@ACG8 did you see the above issue?

**Comment by sIKE23** [comment]
@ACG8 

There are also issues with Initiative and Phase Marker placement. It appears to happen when there are boards that are 5 tiles wide.

**Comment by ACG8** [comment]
Yeah, I saw it. I'll take a look at both issues.

**Comment by sIKE23** [comment]
Going through the maps and validating layout. Will log each issue in its own comment.

**Comment by sIKE23** [comment]
Gauntlet of V'Tar (2 Players) - Player 2 is not being placed properly

![gauntlet of v tar 2 players](https://cloud.githubusercontent.com/assets/5695175/8635208/b0db68fa-27de-11e5-8d49-287fd62897f5.jpg)

**Comment by sIKE23** [comment]
Triumvirate (3 Players) - Player 1 is not laying out properly. The map layout for Mage 1 is/was wrong { "Player" : 1, "Zone" : "1,1" } but the Mage was placed properly. When I changed the start zone to { "Player" : 1, "Zone" : "1,3" } the game started placing him in 1,5 instead of 1.3.

![triumvirate 3 players](https://cloud.githubusercontent.com/assets/5695175/8635345/c6577a1a-27e4-11e5-8cdd-35bf17af20f6.jpg)

**Comment by sIKE23** [comment]
Wartorn Expanse (3 Players) - @startZoneDict=[{ "Player" : 1, "Zone" : "1,3" },{ "Player" : 2, "Zone" : "3,1" },{ "Player" : 3, "Zone" : "4,4" }]

Mage 1 is showing up on 1,4 instead of 1,3.

![wartorn expanse 3 players](https://cloud.githubusercontent.com/assets/5695175/8635850/e4a32582-2802-11e5-816f-eaf2e05b707a.jpg)

**Comment by sIKE23** [comment]
Ziggurat's Rise (3 Players) - same issue as Triumvirate (3 Players)

![ziggurat s rise](https://cloud.githubusercontent.com/assets/5695175/8635871/ecc3c018-2803-11e5-8ed7-6bb1745ca0bd.jpg)

**Comment by sIKE23** [comment]
Unseen Passage - Mages 1 & 3 are not being properly placed. This also shows another issue with object placement. Mage 2 and the DRA overlap.  Thoughts?

![unseen passage](https://cloud.githubusercontent.com/assets/5695175/8635877/8dbd6064-2804-11e5-8f03-97e817bce179.jpg)

**Comment by ACG8** [comment]
I think the above commit should fix all the issues with mage placement.

**Comment by ACG8** [comment]
Though I recommend testing to be sure. I'll look into the DRA overlap problem.

**Comment by ACG8** [comment]
Okay, I think I have an idea. The general problem causing DRA overlap is that we can't predict where mage starting positions will be just by looking at the map, so occasionally the DRA will be assigned to the same location as the mage starting position. The simplest way to fix this is to define the DRA locations in the map file. This can be done by specifying a row (for the "side" option) and a column (for the "bottom" option). I'll figure out a format, and then assign a location for each map. I'm thinking:

```
@DRA=(2,2)
```
Where the first number is the row in which a side-DRA will be placed and the second number is the column in which a bottom-DRA will be placed.

**Comment by sIKE23** [comment]
That sounds great! I am going to make a commit here and be done for the
day. So make sure to sync up before you make changes.

//FC

**Comment by sIKE23** [comment]
The new RDA code places the DiceRollArea card in the proper location weh you select side or bottom but the DiceRollArea Card is set to 0,0 when you roll the dice the first time on the standard map.

**Comment by sIKE23** [comment]
This is much closer and mostly works. If a player has 10 cards lined left to right beside the board the position of the co-ordinates on the table changes. I hope that makes sense....

**Comment by ACG8** [comment]
>If a player has 10 cards lined left to right beside the board the position of the co-ordinates on the table changes. I hope that makes sense....

Not sure what you mean. Are you suggesting that we should do this? Or is this something that is happening (I tested it out, but the cards just continued to line up alongside the board).

**Comment by sIKE23** [comment]
Roll some dice to see what I am talking about....

**Comment by ACG8** [comment]
Still not seeing anything strange (I put out more than 10 cards, then rolled the dice a few times by having one creature attack another. Then I put out more cards, but they behaved as expected).

**Comment by ACG8** [comment]
Are we good on this issue?

**Comment by sIKE23** [comment]
There is an issue that I haven't been able to investigate, but line 184 of
Domination.py throws an error now and I am not sure why.


Otherwise it worked very well last night.

//FC

**Comment by sIKE23** [comment]
Testing now and it no longer seems an issue...

**Comment by sIKE23** [comment]
Looks Good!
