### ISSUE TITLE
Chat Log add font to make it easiser to read

### ISSUE THREAD

**Issue by sIKE23** [sIKE23/Mage-Wars#238]
Using "shouldve known.ttf" as the font. This is the Mage Wars font on the box.

**Comment by ACG8** [comment]
I like the old font better. The new font is difficult to read and all capitalized (which prevents emphasis, such as with the priest's recitations). It is more Mage-Wars-ish, but I don't think it is as user-friendly.

**Comment by sIKE23** [comment]
We have a font that we can agree on!
