### ISSUE TITLE
Add abilty to add Control Markers to Orbs

### ISSUE THREAD

**Issue by sIKE23** [sIKE23/Mage-Wars#240]

**Comment by sIKE23** [comment]
When another player places his control marker on an Orb controlled by another mage it should remove the former controlling mages control marker.

**Comment by ACG8** [comment]
Having 6 different groupactions for control markers is awkward and takes up a lot of space; what if we just have one groupaction, and let it detect the color of the player that calls it? Then players are able to place their own control marker on an orb, but not any other player's color of control marker.

**Comment by sIKE23** [comment]
That is what I am working on, but we get back into that crud of Player and
Game setup that is all bunk. Right now players pick a button color that
equates to a Hex value. I have been working on and modeling my proposal
from a week or so ago. This is what I have for Player Color Selection in it:

playerColorDict = {
        1 : {"Color":"Red", "Hex":"#de2827",
"ControlMarker":"ControlMarkerRed"}, #Red - R=222 G=40  B=39
        2 : {"Color":"Blue", "Hex":"#171e78",
"ControlMarker":"ControlMarkerBlue"}, #Blue - R=23  G=30  B=120
        3 : {"Color":"Green", "Hex":"#01603e",
"ControlMarker":"ControlMarkerGreen"}, #Green - R=1   G=96  B=62
        4 : {"Color":"Yellow", "Hex":"#f7d917",
"ControlMarker":"ControlMarkerYellow"}, #Yellow - R=247 G=217 B=23
        5 : {"Color":"Purple", "Hex":"#c680b4",
"ControlMarker":"ControlMarkerPurple"}, #Purple - R=198 G=128 B=180
        6 : {"Color":"Grey", "Hex":"#c0c0c0",
"ControlMarker":"ControlMarkerGrey"} #Grey - R=192 G=192 B=192
             }

If you had time to play/fiddle around I would show you what I got, so far.
I like you do not have lots of time so it hasn't gotten very far....

We have time now as Domination as been delayed for a several more months. I
have asked AW thoughts on us releasing early and have not heard back.

//FC

**Comment by sIKE23** [comment]
Heard back from Aaron, they would like for us to release after Gencon. So I
moved the Domination release out to August 8th. They will even give us an
announcement on the AW website. I think this is doable correct?

Let me know what you think.

//FC

**Comment by ACG8** [comment]
Yes, I think August 8th is doable. Definitely nice to have an announcement on the website.

**Comment by sIKE23** [comment]
This is done and has evolved into #255
