### ISSUE TITLE
When casting a spell, canceling the askInterger window for casting cost, should cancel the casting of the spell 

### ISSUE THREAD

**Issue by sIKE23** [sIKE23/Mage-Wars#245]

**Comment by sIKE23** [comment]
@ACG8 - I tried to figure this one out, but I was not able to trace why canceling the casting cost was not canceling the attack, but I am getting lost in the "steps" functions in attacks.py. Could you take a look at this for me?

**Comment by ACG8** [comment]
Sure. I should be able to do some work on this this weekend.

**Comment by sIKE23** [comment]
I was finally able to figure it out. I was looking in the wrong spot! Had to go back to the onTargetCardArrow function to capture the cancelation of the spell being cast. I also moved flipping the card over until after the cost was paid and the spell resolved.

**Comment by sIKE23** [comment]
This works like I would expect it to now....
