### ISSUE TITLE
Lion Savagery should prompt for Charge Bonus

### ISSUE THREAD

**Issue by sIKE23** [sIKE23/Mage-Wars#250]
I was not able to trace to "when" this prompt triggers. I have moved the reveal up to before the RollDiceStep but it is still not asking to apply the Charge Bonus.

**Comment by sIKE23** [comment]
@ACG8 
I played with this for several hours today. First I do not see nor get how the Charge code works. I see on line 57 of attacks.py you prompt to see if the player wishes to apply the Charge bonus for this attack. And as far as I can tell, you store the fact that the player selected "Yes" and that is all. I never see anywhere else in the script that you add the charge bonus to the base attack. So that baffles me.

Second this works great with revealed the already revealed Enchantment(s) and when the trait is native to the attacker (Bloodcrag Minotaur) the problem is that it doesn't handle when the Lion Savagery is hidden at the beginning of the attack sequence as the Apply Charge Bonus question happens way before the player is prompted to reveal the Enchantment. Now I think that needs to land in the interimStep() function after line 738 (selfAttached = revealAttachmentQuery([attacker,defender],prevStepName)) but I am then back to point 1 above....

So Obi-wan tell me what I am missing...

**Comment by ACG8** [comment]
> I never see anywhere else in the script that you add the charge bonus to the base attack. So that baffles me.

It is in line 349, in the getAdjustedDice() function:
```
if attack.get('RangeType') == 'Melee': attackDice += aTraitDict.get('Melee',0) + (aTraitDict.get('Charge',0) if hasCharged(attacker) else 0)
```
where ```hasCharged(card)``` consults the game history to see if the player selected charge for that card.

>Second this works great with revealed the already revealed Enchantment(s) and when the trait is native to the attacker (Bloodcrag Minotaur) the problem is that it doesn't handle when the Lion Savagery is hidden at the beginning of the attack sequence as the Apply Charge Bonus question happens way before the player is prompted to reveal the Enchantment.

Yes, I can see how this would be a problem. I suppose one way to fix it is to give the charge prompt if there is a hidden enchantment attached to the creature (that you control) that could potentially give a charge bonus.

**Comment by sIKE23** [comment]
@ACG8 
I know it was in there somewhere and I even remember looking at that particular line. I looked again tonight. Still not able to resolve.

**Comment by ACG8** [comment]
Okay, I can take a look later today.

**Comment by ACG8** [comment]
This should solve the problem, for now at least.

**Comment by sIKE23** [comment]
What does the "1 for c in"


I get the "for c in" part but not the "1"

**Comment by ACG8** [comment]
The 1 is irrelevant; you could use pretty much anything (```"a" for c```, ```500 for c```, ```{"blergh":"blorgh"} for c```, etc.). The important thing is that the list is only non-empty (and therefore evaluates to True) if Lion Savagery is attached. The 1 is just an arbitrary variable used to populate the list.

**Comment by sIKE23** [comment]
Charge!
