### ISSUE TITLE
Automate Helm of Fear

### ISSUE THREAD

**Issue by sIKE23** [sIKE23/Mage-Wars#251]
Trying to see if my understanding of the AvoidAttackStep is sound.

**Comment by sIKE23** [comment]
@ACG8 

Can you take a quick look at this code change to see if I did it correctly? Starts at lines 803(ish) in attacks.py

**Comment by ACG8** [comment]
Almost. I found a few errors; if you don't mind, I'll fix them and upload.

**Comment by sIKE23** [comment]
I do not mind that is why I asked....

**Comment by sIKE23** [comment]
Pie in the sky request :) Hunting Bow I have been thinking on it. But I do
not think that we have memory of damage done by an Animal Creature. This
would be a 2.x release is my guess.

**Comment by ACG8** [comment]
Could probably be done, but might be better to wait for 2.x. Though I might end up doing it just for fun, if it isn't too hard.

**Comment by ACG8** [comment]
Okay, give it a try now.

**Comment by sIKE23** [comment]
Ok Working Fine!
