### ISSUE TITLE
Add Domination Tiles special abilities to Rulings/Clarifications  

### ISSUE THREAD

**Issue by sIKE23** [sIKE23/Mage-Wars#252]

**Comment by sIKE23** [comment]
@ACG8 
Do you think this is a good idea? I was just going to grab the entries from the manual and add them directly to the text file. Or should I do something different, or not at all?

**Comment by ACG8** [comment]
Yes, this is a good idea. Definitely something players may forget.

**Comment by sIKE23** [comment]
Done
