### ISSUE TITLE
Prevent card placement automation from moving scenario cards

### ISSUE THREAD

**Issue by sIKE23** [sIKE23/Mage-Wars#253]
Right now if you change maps, then load a deck if you are the owner of the scenario cards, they are all moved to your default card area beside the board.

Couple of ways to fix this, I think the easiest is to create a group, it does nothing other than create Player0, then once we create the gameboard pieces and objects we change the ownership to Player0

thoughts?

**Comment by sIKE23** [comment]
Sorry I thought I added you as the assignee to this last night....

**Comment by ACG8** [comment]
No problem. I'm taking a look at these now.

**Comment by ACG8** [comment]
I am unable to reproduce this bug. I did the following:

1. Load map
2. Load deck
3. Load map

I also tried

1. Load map
2. Load map
3. Load deck

And the game is behaving as expected. What do I need to do to reproduce this?

**Comment by sIKE23** [comment]
Yeah, it is hard to reproduce, it dawned on me last night when it happened
what was going on. I think it is more of a two player thing than a one
player.

**Comment by ACG8** [comment]
Okay, I'll try reproducing it with two players.

**Comment by ACG8** [comment]
Okay, I see it. Working on a fix now...

**Comment by ACG8** [comment]
Okay, I think I've solved this one, but you should try it out to be sure. The ```CreateIniToken()``` function was causing all the cards to be returned to their owners; I just told it to exclude cards with the ```card.special == "scenario"``` property.

**Comment by sIKE23** [comment]
This one is finally working as expected....
