### ISSUE TITLE
Handle Attacking/Touching Orbs

### ISSUE THREAD

**Issue by sIKE23** [sIKE23/Mage-Wars#255]
Keep the rules in mind:

When an Orb is touched by your Mage, or a creature they control, it changes control:

• If the orb was neutral, you now control it. Place one of your control markers on it.
• If it was controlled by another player, it becomes neutral again instead.

Remove that player’s colored control marker.

Orbs begin the game powered “off”. The first time that each orb is touched by a Mage,
or a creature they control, it becomes powered “on” (flip the orb marker to its “on” side).

Once they are powered “on”, they remain powered “on” for the rest of the game, even if
their control changes.

Note that some zones may have more than one orb in them. It is possible for each Orb
to be controlled by a different Mage or team.

**Comment by sIKE23** [comment]
When an attack happens, check to see if it is an Orb and if so, stop the attack sequence and then check to see if there a Control Marker on it, if not place Player Control Marker on it. If there is remove player control marker from it. As a part of placing a Control Marker on it we already turn the Orb on. It should never get turned back off.

**Comment by sIKE23** [comment]
@ACG8 
Just making sure you didn't miss this submission.

**Comment by ACG8** [comment]
Right, got it. Should have time to code this weekend (though I know I've said that the past few weekends and haven't...)

**Comment by sIKE23** [comment]
@ACG8 
As always if you see a way to make it better feel free to tweak the code if have submitted.

**Comment by sIKE23** [comment]
You light up my V'Tar!
