### ISSUE TITLE
Block is not interacting with Wall of Thorns properly

### ISSUE THREAD

**Issue by sIKE23** [sIKE23/Mage-Wars#260]
Thorn + Push: Victim revealed Block, that did not block one single 2 dice attack, but the entire attack action from the wall.

**Comment by sIKE23** [comment]
Not sure of how to fix this one....

**Comment by ACG8** [comment]
Wall of Thorn's attack is unavoidable, so Block should not prevent it (and, in fact, does not based on my latest test).

1. Created Beastmaster and Wall of Thorns.
2. Enchanted BM with Block
3. Wall of Thorns attacks BM
4. Revealed Block
5. Wall of Thorns hit BM 5 times, as it should.

In short, I have not been able to reproduce this issue.

**Comment by sIKE23** [comment]
I agree there is nothing wrong, closing/won't fix
