### ISSUE TITLE
Dancing Scimitar should store that it has been used during the round

### ISSUE THREAD

**Issue by sIKE23** [sIKE23/Mage-Wars#262]
Mage has one of these equipped and is attacked, prompt to use Scimitar as a defense is "yes" everything works as expected, Mage now attacks and has the option to use the Scimitar's attack as one of his options. This is not allowed as it is an either/or option but not both.

**Comment by ACG8** [comment]
Okay, this fix is in. Give it a try.

**Comment by sIKE23** [comment]
Can I start the merge this evening?

**Comment by ACG8** [comment]
Sure. I will stop working on it now. I will have no further commits in the works until you tell me that the merging is complete.

**Comment by sIKE23** [comment]
Ooh no if you are working you keep going

**Comment by ACG8** [comment]
No, I'm not working.

**Comment by ACG8** [comment]
I don't have anything in the works.

**Comment by sIKE23** [comment]
Ok it is done, you should be working out of the master branch now, you can
go into manage braches and remove + delete the Domination, Q1, and Q2
Branches (unless you have some work there you don't want to loose) I will
create a Q3 branch soon after we roll out this release.

//FC

**Comment by sIKE23** [comment]
He only does things once now!
