### ISSUE TITLE
Consolidate toggleable game options into a single group action

### ISSUE THREAD

**Issue by ACG8** [sIKE23/Mage-Wars#265]
Many of the game options are simple toggle options. It is awkward having a separate groupaction for each one, so I want to consolidate them under a single groupaction. You can see what I am thinking in the commit I am about to upload. By handling game options through a color-coded askChoice menu, it becomes easier for players to see what the current settings are.

**Comment by sIKE23** [comment]
Good idea, I was going to go a bit further with my suggestion, Automation
On/Automation Off, with the Default being on.

//FC

**Comment by sIKE23** [comment]
With that all said, I really like the options menu!
