### ISSUE TITLE
BC should take Unmovable into account and give Daze instead of Slam condition

### ISSUE THREAD

**Issue by sIKE23** [sIKE23/Mage-Wars#279]

**Comment by ACG8** [comment]
It should be doing this already. Is this not happening for a certain test case?

**Comment by sIKE23** [comment]
I got that report in a chat from OCTGN, since there is no way to archive or
copy these messages I went ahead and opened an issue so I wouldn't forget
to follow and attempt to reproduce.

//FC

**Comment by sIKE23** [comment]
I should of noted that the Unmovable trait was granted by Eagle Claw boots.

**Comment by ACG8** [comment]
Ok, that might make a difference. I'll take a look.

**Comment by sIKE23** [comment]
I have merged all of the work back into Master, if you find that you need
to fix something, you can do it in that branch and I will pull it over to
Q3, or I can pull it the other way if you want to stay in the Q3 branch.

//FC

**Comment by sIKE23** [comment]
I have fixed this,

the set data for the boots needed [Unmovable]

**Comment by sIKE23** [comment]
This brought up an implementation question, how does equipment apply to a Mage? Mainly interested on how the BC knows its "my" equipment. What happens if it gets stolen by another mage?
