### ISSUE TITLE
Migrate Game Definition to the 3.1.0.2 API

### ISSUE THREAD

**Issue by sIKE23** [sIKE23/Mage-Wars#292]
https://github.com/octgn/OCTGN/wiki/OCTGN-Python-3.1.0.2-API-Reference

**Comment by sIKE23** [comment]
@ACG8 
I am unable to Bind a Hurl Rock to an Elemental Wand, do you think it could have something to do with the API migration?

**Comment by ACG8** [comment]
Figuring out the problem now. There seems to be an issue with the onMoveCards function.

**Comment by sIKE23** [comment]
I figured this out, it was a formatting error on my part trying to merge
what was over in the V2 branch into the V1 branch with the mount work
added. I also went ahead and normalized the mount code to reflect the
changes you made to the code section over in V2. I will push this fix out
in a while, I am trying to take another pass at the Rune of Power code.

//FC

**Comment by sIKE23** [comment]
Reopening since we are now migrating v1 to this version of the API
