### ISSUE TITLE
Conjurations should not get Slammed/Stunned/Weak type conditions

### ISSUE THREAD

**Issue by sIKE23** [sIKE23/Mage-Wars#297]

**Comment by sIKE23** [comment]
I think this was a part of the code you were going to re-write anyways, but I am not sure.

**Comment by ACG8** [comment]
This should already be prevented by line 342, which states:

```
[if] (e in ['Bleed','Stuck','Stun','Daze','Cripple','Weak','Slam','Stagger'] and defender.Type != 'Creature')): illegalEffect = True
```

Is this happening in games? If so, under what circumstances?

**Comment by sIKE23** [comment]
Surging Wave was placing Slam markers on a Temple of the Dawnbreaker last
night in a game I was watching. I looked at the same code and came to the
same conclusion, which is why the Issue was given to you. :)

//FC

**Comment by ACG8** [comment]
All right, I'll take a look.

**Comment by ACG8** [comment]
I am unable to reproduce this issue (I cast surging wave on the ToD and rolled a 9 on the d12, but there was no slam applied). Perhaps we should close this issue? Unless you can tell me how to reproduce this.

**Comment by sIKE23** [comment]
Did you try it with 2 players?

**Comment by ACG8** [comment]
Oh, no. I'll try that.

**Comment by ACG8** [comment]
Nope, even with 2 players, I cannot reproduce this bug. I have one mage attack another mage's ToD with Surging Wave and roll an 8, but no slam condition is inflicted.

**Comment by sIKE23** [comment]
I can't reproduce now either...I will close.

//FC

**Comment by sIKE23** [comment]
Closing.....
