### ISSUE TITLE
Spellbook Validator not working

### ISSUE THREAD

**Issue by ACG8** [sIKE23/Mage-Wars#305]
I was trying to update one of my druid spellbooks and got the validation error 

"ERROR: The card Seedling Pod is not legal in a none in deck deck"

I suspect that the change of Mage type from Mage to Creature may have broken the mechanism for determining which Mage is in control of a spellbook, and hence the validator believes that my spellbook does not have a mage at all.

**Comment by sIKE23** [comment]
Install the MSI from the 2.0.x kit......

**Comment by ACG8** [comment]
Ah, okay. Didn't realize that. Where is that located, exactly? I tried the one in the dev folder and the one in the plugins, but neither of them seem to be correct.

**Comment by sIKE23** [comment]
nope, copy the Dll in the new commit to the plugin folder manually.....

//FC

**Comment by ACG8** [comment]
All right, I have it working. Closing this issue.
