### ISSUE TITLE
Critical Damage trait not interacting correctly with Veteran's Belt

### ISSUE THREAD

**Issue by ACG8** [sIKE23/Mage-Wars#308]
The Critical Damage Trait should be mitigated by Veteran's Belt (I think). Currently, it has been reported to not work (i.e. the Crit damage is not transformed into normal damage).

**Comment by ACG8** [comment]
I am unable to reproduce this bug; in my tests, the Veteran's Belt performs as intended. Do you have any more information about this problem?

**Comment by sIKE23** [comment]
This was your issue that you opened! I don't know if it is an issue or not.

**Comment by ACG8** [comment]
Oh wow... sorry, I'm not sure how I made that mistake. That's pretty bad of me.

**Comment by ACG8** [comment]
So... I opened this issue, and then apparently forgot it existed (probably because I did not assign it to myself). Anyway, the problem is fixed now; critical damage attacks (such as the Psylok's) interact correctly with the vet's belt.
