### ISSUE TITLE
Force Ring Discount not working

### ISSUE THREAD

**Issue by sIKE23** [sIKE23/Mage-Wars#311]
There is also a problem with Force Ring and Force Hammer. If you have 8 Mana and the Ring is ready, you should be able to attack with Force Hammer ... but the Automation doesn't work. The ring does not count somehow. You have to add 1 Mana manually and decrease it again after the attack is made.

**Comment by ACG8** [comment]
You want me to fix this in the master branch, right? Not Q3?

**Comment by sIKE23** [comment]
Correct

**Comment by ACG8** [comment]
I have figured out the problem; it is an issue with the a way legal attacks are computed (which does not take discounts into account. This error will only occur on discounts for attack spells. Working on a fix now.

**Comment by sIKE23** [comment]
Verified as resolved with Schwenk
