### ISSUE TITLE
Rework card attachment system and add mount-type attachment

### ISSUE THREAD

**Issue by sIKE23** [sIKE23/Mage-Wars#318]

**Comment by sIKE23** [comment]
My thoughts for the mechanic is to create a 3 style of attaching cards to one another. With have AttachCard, BindCard, and we would add MountCard. 

It would work much like Bind, a legal Mounter and Mount, Draw Arrow from Mounter to Mount, prompt does {mage}  wish to mount {creature}? If yes, move the mounting mages card with its right edge touching the left edge of the mounts card.

**Comment by ACG8** [comment]
Sure. I've been thinking it is about time to redo the card attachment functions anyway; I had a nice idea for a recursive alignment function.

**Comment by sIKE23** [comment]
Sounds interesting, I know you have redone the targeting aspect of it already. Does that work for bindings also?

**Comment by ACG8** [comment]
No, not yet. Bindings are still hardcoded.

**Comment by sIKE23** [comment]
getting this error
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'remoteAlign' is not defined
remoteAlign([{'Y': -250.0, 'X': -154.0, 'cardId': 196639, 'prevCardIds': [131078]}],[Player(2),Player(3)])
```

**Comment by sIKE23** [comment]
@ACG8 
Ignore this they were playing with different versions of the script.

**Comment by ACG8** [comment]
Okay, the first implementation of mount is done. It is crude, but it works.

**Comment by sIKE23** [comment]
Looks good for now...
