### ISSUE TITLE
Multiple Attacks (Triple Strike/Wall of Thorns) are broken

### ISSUE THREAD

**Issue by sIKE23** [sIKE23/Mage-Wars#323]
The BC is only making the first attack.

**Comment by ACG8** [comment]
I didn't find any issue with the Wall of Thorns. For triplestrike, I assume the issue arose when testing Ludwig Boltstorm? I checked his xml file, and there was a space after triplestrike, causing the trait to be read as "Triplestrike ", which the BC does not recognize. Not sure how the space got in there, or whether it has always been there.

**Comment by sIKE23** [comment]
Interesting, I will try again this evening, have to go into the office
today...ick.

//FC

**Comment by sIKE23** [comment]
verified as fixed with Schwenkgott
