### ISSUE TITLE
Allow the same Hidden Enchantment from different controllers to attach to the target

### ISSUE THREAD

**Issue by sIKE23** [sIKE23/Mage-Wars#335]

**Comment by sIKE23** [comment]
Otherwise it gives away that the Enchantment is already attached.....

**Comment by ACG8** [comment]
I tested this, and there does not appear to be an issue. I had two beastmasters cast a face down bear strength on the same object, and they were able to do so without any difficulty. Any further details on this bug?

**Comment by sIKE23** [comment]
This was reported by Mystery, I will ask him a bit more about his setup.

**Comment by sIKE23** [comment]
Unable to reproduce, I am closing this out.
