### ISSUE TITLE
Forcefield automation not working properly

### ISSUE THREAD

**Issue by sIKE23** [sIKE23/Mage-Wars#337]
Schwenkgott: 

Forcemaster with Forcefield and Doublestriking Galvitar hits enemy. Enemy reveals reverse attack, so forcemaster hits herself (with the first strike). This attack should be blocked by Forcefield. The Automation however rolls the attack, applies damage (Prompt) to Forcemaster and then the forcefield absorbs the second attack.

The second attack should go on the enemy, I think

So two bugs at once. Forcefield is not absorbing the attack ... and second strike at wrong target

**Comment by ACG8** [comment]
Actually, the only issue is that the second attack is being reflected.

Forcefield says:
"Whenever you are attacked, before the Avoid Attack step, you must remove a token. If you do, that attack is cancelled."

Reverse Attack says:
"the attacker [becomes] the target of the attack for the next two steps ("Roll Dice" and "Damage and Effects"

So the forcefield never has a chance to trigger on the first reflected attack.

I will see if I can fix the second problem; the issue, essentially, is that reverse attack currently just overwrites the target of the attack. I'll have to add some method of storing the attack's original target.

**Comment by sIKE23** [comment]
This is working fine now!
