### ISSUE TITLE
Bear Strength does not buff attack when revealed during counterstrike step

### ISSUE THREAD

**Issue by sIKE23** [sIKE23/Mage-Wars#343]
Lightning Raptor attacks Johktari Beastmaster with Electric Bite!
sike23 rolls 5 attack dice 
sike23 rolled 0 normal damage, 2 critical damage, and 3 on the effect die
Lightning Raptor inflicts 2 damage on Johktari Beastmaster... (a below average roll)
Johktari Beastmaster retaliates with Basic Melee Attack!
schwenkgott pays 3 mana.
schwenkgott reveals Bear Strength!
schwenkgott rolls 3 attack dice 
schwenkgott rolled 0 normal damage, 4 critical damage, and 4 on the effect die
<schwenkgott> see?
Johktari Beastmaster inflicts 4 damage on Lightning Raptor! (an above average roll)
<schwenkgott> revealed bear str and only 3 dice
****

**Comment by sIKE23** [comment]
What would be really cool, looking at this output, is if we noted that the JBM was guarding:

```
Lightning Raptor attacks the Guarding Johktari Beastmaster with Electric Bite!
```

**Comment by ACG8** [comment]
Should be easy enough to add (re: recognizing guarding). You just have to check whether there is a guard marker.

Was occupied this week, but may have some time this weekend to fix some of these issues.

**Comment by ACG8** [comment]
I found the issue. Everything is working perfectly. I am assuming that your Johktari Beastmaster had a stagger when you tested this, right? (from a previous attack from the lightning raptor). When I have the JBM attack the lightning raptor with no stagger condition, she has 5 attack. So I think the problem is that you successfully implemented stagger :)

**Comment by sIKE23** [comment]
Was there no issue?

**Comment by ACG8** [comment]
Yeah. As far as I can tell, there is no problem.

**Comment by sIKE23** [comment]
What about the guarding bit?

**Comment by ACG8** [comment]
Haven't worked that in yet, but that is a separate issue. Perhaps we should change the title of this issue to focus on that.

**Comment by sIKE23** [comment]
Close this as won't fix, open another one?

**Comment by ACG8** [comment]
Sure.
